### ISSUE TITLE
On the 2022/BWE_TUNet folder, how to inference in real-time?

### ISSUE THREAD

**Issue by Hen-jo** [CARNIVAL-IITP/Bandwidth-extension#1]
On the 2022/BWE_TUNet folder, how to inference in real-time?

**Comment by utahboy3502** [comment]
> On the 2022/BWE_TUNet folder, how to inference in real-time?

Please refere to the section Test on Readme.md in the 2022/BWE_TUNet folder
Change parameter as following:
```
ONNX_ZERO = True
```

After transforming the trained model into ONNX, run main.py --mode eval

Basically, I am using overlap add method with zero padding to achieve real-time processing as the picture below:

![제로패딩](https://user-images.githubusercontent.com/82129086/207261510-6fea143b-c3a8-4f8a-8a2b-172ce4a8e0fd.png)
