### ISSUE TITLE
On the 2022/BWE_TFiLM folder, what kind of face mask used for reproducing dataset?

### ISSUE THREAD

**Issue by hylee-250** [CARNIVAL-IITP/Bandwidth-extension#2]
On the 2022/BWE_TFiLM folder, what kind of face mask used for reproducing dataset?

**Comment by utahboy3502** [comment]
> On the 2022/BWE_TFiLM folder, what kind of face mask used for reproducing dataset?

I used KF80, 94, 99, and dental (surgical) masks that can be found in Korea.
