### ISSUE TITLE
Can you please share the sample of output from the proposed algorithm of 2022/BWE_TFiLM after processing noisy input?

### ISSUE THREAD

**Issue by kimyeondu** [CARNIVAL-IITP/Bandwidth-extension#3]
Can you please share the sample of output from the proposed algorithm of 2022/BWE_TFiLM after processing noisy input?

**Comment by utahboy3502** [comment]
I have added the sample/ folder with clean audio (_hr), noisy audio (_lr), and the output .wav file.

I am attaching the spectrogram of each to visualize how the proposed algorithm is effective.

![image](https://user-images.githubusercontent.com/82129086/207258489-3c83c35c-55e6-4a01-960a-6b72872c926a.png)
